version: '3.7'
services:
  mongo:
    image: mongo:4.2.3-bionic
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /mnt/mongodb:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
